/**
 * JJB Schema -> TypeScript source (`defineSchema(...)` block).
 *
 * Deterministic output: fields in source order, criteria keys in source
 * order, two-space indent. The generated code targets the published
 * `jev-json-builder` entry point (configurable via `importFrom`).
 */

import type { Field, Schema } from "../core/schema.js";

import type { SchemaSource } from "./types.js";
import { exportNameFor } from "./util.js";

export type RenderOptions = {
  /** Module specifier for the import statement. Default: `jev-json-builder`. */
  importFrom?: string;
  /** Emit a header comment with the source origin. Default: true. */
  header?: boolean;
  /** Include `optional: true` markers explicitly. Default: true. */
  markOptional?: boolean;
};

function renderString(value: string): string {
  return JSON.stringify(value);
}

function renderCriteria(criteria: Record<string, string | null>, indent: string): string {
  const entries = Object.entries(criteria);
  if (entries.length === 0) return "{}";
  const lines = entries.map(
    ([key, desc]) => `${indent}  ${renderString(key)}: ${desc === null ? "null" : renderString(desc)},`,
  );
  return `{\n${lines.join("\n")}\n${indent}}`;
}

function renderField(field: Field, indent: string, markOptional: boolean): string {
  const options: string[] = [`question: ${renderString(field.options.question)}`];
  if (field.options.optional && markOptional) options.push("optional: true");
  if (field.options.threshold !== undefined) {
    options.push(`threshold: ${String(field.options.threshold)}`);
  }
  const opts = `{ ${options.join(", ")} }`;

  switch (field.kind) {
    case "enum":
      return `enumField(\n${indent}  ${renderCriteria(field.criteria, `${indent}  `)},\n${indent}  ${opts},\n${indent})`;
    case "score": {
      const levels = field.levels.map(renderString).join(", ");
      return `scoreField([${levels}], ${opts})`;
    }
    case "int":
      return `intField(${opts})`;
    case "number":
      return `numberField(${opts})`;
    case "string":
      return `stringField(${opts})`;
    case "date":
      return `dateField(${opts})`;
  }
}

function usedConstructors(schema: Schema): string[] {
  const used = new Set<string>(["defineSchema"]);
  for (const field of Object.values(schema)) {
    switch (field.kind) {
      case "enum":
        used.add("enumField");
        break;
      case "score":
        used.add("scoreField");
        break;
      case "int":
        used.add("intField");
        break;
      case "number":
        used.add("numberField");
        break;
      case "string":
        used.add("stringField");
        break;
      case "date":
        used.add("dateField");
        break;
    }
  }
  const order = [
    "defineSchema",
    "enumField",
    "scoreField",
    "intField",
    "numberField",
    "stringField",
    "dateField",
  ];
  return order.filter((name) => used.has(name));
}

/** Render one schema source as a complete TS module (import + export). */
export function renderSchemaSource(
  source: SchemaSource,
  options: RenderOptions = {},
): string {
  return renderSchemaSources([source], options);
}

/**
 * Render several schema sources in one module. The import statement is
 * deduplicated and covers every constructor actually used.
 */
export function renderSchemaSources(
  sources: SchemaSource[],
  options: RenderOptions = {},
): string {
  const importFrom = options.importFrom ?? "jev-json-builder";
  const markOptional = options.markOptional ?? true;
  const header = options.header ?? true;

  const used = new Set<string>();
  for (const source of sources) {
    for (const name of usedConstructors(source.schema)) used.add(name);
  }
  const order = [
    "defineSchema",
    "enumField",
    "scoreField",
    "intField",
    "numberField",
    "stringField",
    "dateField",
  ];
  const imports = order.filter((name) => used.has(name));

  const parts: string[] = [];

  if (header) {
    parts.push(
      "// Generated by jev-json-builder schema ingestion. Review question wording —",
      "// Jev answers are only as good as the questions.",
    );
    for (const source of sources) {
      parts.push(`// Source: ${source.origin}`);
      for (const diag of source.diagnostics) {
        parts.push(`//   [${diag.level}] ${diag.path ? `${diag.path}: ` : ""}${diag.message}`);
      }
    }
    parts.push("");
  }

  parts.push(`import { ${imports.join(", ")} } from ${renderString(importFrom)};`);
  parts.push("");

  for (const source of sources) {
    const exportName = exportNameFor(source.name);
    const fields = Object.entries(source.schema);

    parts.push(`export const ${exportName} = defineSchema({`);
    if (fields.length === 0) {
      parts.push("  // No mappable fields — see diagnostics above.");
    }
    for (const [name, field] of fields) {
      const key = /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name) ? name : renderString(name);
      const body = renderField(field, "  ", markOptional);
      parts.push(`  ${key}: ${body},`);
    }
    parts.push("});");
    parts.push("");
  }

  return parts.join("\n").replace(/\n{3,}/g, "\n\n").trimEnd() + "\n";
}